"""Generate the PWA / home-screen app icon (the Plasma Boy face, matching the favicon) as a PNG
data URI, written into src/config/appIcon.ts. Pure standard-library (zlib) PNG encoder so it needs
no image tooling. Regenerate with:  python3 scripts/gen_icon.py
"""
import zlib
import struct
import base64
import os

W = H = 512

# Palette (matches the in-page favicon in index.html).
BG = (0x5f, 0xb7, 0xe8, 255)
YEL = (0xff, 0xd5, 0x4f, 255)
ORA = (0xe0, 0xa8, 0x00, 255)
SKIN = (0xff, 0xcc, 0x99, 255)
EYE = (0x1a, 0x1a, 0x2e, 255)
BODY = (0x7c, 0x4d, 0xff, 255)
COL = (0xff, 0x6f, 0x3c, 255)

px = [BG] * (W * H)


def rect(x, y, w, h, c):
    for yy in range(y, y + h):
        if 0 <= yy < H:
            base = yy * W
            for xx in range(x, x + w):
                if 0 <= xx < W:
                    px[base + xx] = c


# Draw the face on the favicon's 16-grid, scaled and centred so the important content sits inside
# the maskable safe zone (OS icons get their corners rounded / cropped).
S, O = 24, 64  # 16*24 = 384, centred in 512 (64px padding each side)


def g(gx, gy, gw, gh, c):
    rect(O + gx * S, O + gy * S, gw * S, gh * S, c)


g(3, 2, 10, 3, YEL)                       # visor
g(2, 3, 2, 2, ORA); g(12, 3, 2, 2, ORA)   # visor sides
g(4, 4, 8, 6, SKIN)                       # face
g(4, 4, 2, 2, YEL); g(10, 4, 2, 2, YEL)   # face top corners
g(6, 6, 1, 2, EYE); g(9, 6, 1, 2, EYE)    # eyes
g(3, 10, 10, 6, BODY)                     # body
g(3, 10, 10, 1, COL)                      # collar


def encode_png(pixels, w, h):
    raw = bytearray()
    for y in range(h):
        raw.append(0)  # filter type 0 (none) for this scanline
        base = y * w
        for x in range(w):
            raw += bytes(pixels[base + x])
    comp = zlib.compress(bytes(raw), 9)

    def chunk(typ, data):
        return (struct.pack('>I', len(data)) + typ + data
                + struct.pack('>I', zlib.crc32(typ + data) & 0xffffffff))

    ihdr = struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0)  # 8-bit RGBA
    return (b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', ihdr)
            + chunk(b'IDAT', comp) + chunk(b'IEND', b''))


data = encode_png(px, W, H)
uri = 'data:image/png;base64,' + base64.b64encode(data).decode()

out = os.path.join(os.path.dirname(__file__), '..', 'src', 'config', 'appIcon.ts')
with open(out, 'w') as f:
    f.write('// Generated by scripts/gen_icon.py — the home-screen app icon (Plasma Boy face) as a\n')
    f.write('// PNG data URI, used by the PWA manifest and apple-touch-icon. Regenerate with:\n')
    f.write('//   python3 scripts/gen_icon.py\n')
    f.write(f'export const APP_ICON_PNG = "{uri}";\n')

print(f'wrote {out} — png {len(data)} bytes, data-uri {len(uri)} chars')
